language: c
compiler: gcc
dist: xenial
addons:
  apt:
    packages:
      - libconfuse-dev
      - cramfsprogs
      - dosfstools
      - e2fsprogs
      - fakeroot
      - genext2fs
      - genisoimage
      - mtd-utils
      - mtools
      - qemu-utils
      - squashfs-tools
      - device-tree-compiler
      - u-boot-tools
script:
  - ./autogen.sh
  - ./configure
  - make distcheck
after_failure:
  - find -name test-suite.log -print0 | xargs -0 cat
