language: c
compiler: gcc
dist: trusty
addons:
  apt:
    packages:
      - libconfuse-dev
      - cramfsprogs
      - dosfstools
      - fakeroot
      - genext2fs
      - genisoimage
      - mtools
      - qemu-utils
      - squashfs-tools
# FIXME: dtc on travis is too old
#      - device-tree-compiler
#      - u-boot-tools
script:
  - ./autogen.sh
  - ./configure
  - make distcheck
after_failure:
  - cat genimage-*/_build/test-suite.log
